/* Copyright 2023 RephlexZero (@RephlexZero)
SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once

#define MATRIX_ROWS 6
#define MATRIX_COLS 15

#define MUXES 6
#define MUX_PINS { A2, A3, A6, A7, B12, B14 }
#define MUX_ADC { 1, 1, 2, 2, 4, 4}
#define MUX_SELECTOR_BITS 4
#define MUX_SELECTOR_PINS { B11, B10, B1, B2 }

#define MUX_CHANNELS ( 1 << MUX_SELECTOR_BITS )


#define WS2812_PWM_DRIVER PWMD16
#define WS2812_PWM_CHANNEL 1
#define WS2812_PWM_PAL_MODE 1
#define WS2812_DMA_STREAM STM32_DMA1_STREAM3
#define WS2812_DMA_CHANNEL 3

#define EECONFIG_KB_DATA_SIZE 6

#define DEBUG_ENABLE
#define DEBUG_MATRIX_SCAN_RATE

#define I2C1_SCL_PIN B6
#define I2C1_SDA_PIN B7
#define I2C1_CLOCK_SPEED 400000
#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_16_9
#define OLED_BRIGHTNESS 128
#define OLED_UPDATE_INTERVAL 1000

#define ADC_RESOLUTION      ADC_CFGR_RES_12BITS

#define CALIBRATION_RANGE 255

#define AUDIO_PIN A4
#define AUDIO_PIN_ALT_AS_NEGATIVE
#define AUDIO_PIN_ALT A5
#define AUDIO_INIT_DELAY 250
#define AUDIO_DAC_SAMPLE_MAX 4095U
#define TEMPO_DEFAULT 70
#ifdef AUDIO_ENABLE
#   define STARTUP_SONG SONG(ZELDA_PUZZLE)
#   define GOODBYE_SONG SONG()
#endif

