/* Copyright 2023 RephlexZero (@RephlexZero)
SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once

#define MATRIX_ROWS 6
#define MATRIX_COLS 15

#define MUXES 6
#define MUX_PINS { A0, A1, A6, A7, B1, B12 }
#define MUX_ADCS { 1, 1, 2, 2, 3, 4 }
#define MUX_SELECTOR_BITS 4
#define MUX_SELECTOR_PINS { B4, B5, B6, B7 }

#define MUX_CHANNELS ( 1 << MUX_SELECTOR_BITS )


#define WS2812_PWM_DRIVER PWMD1
#define WS2812_PWM_CHANNEL 4
#define WS2812_PWM_PAL_MODE 2
#define WS2812_DMA_STREAM STM32_DMA1_STREAM5
#define WS2812_DMA_CHANNEL 5

#define EECONFIG_KB_DATA_SIZE 6

//#define DEBUG_ENABLE
#define DEBUG_MATRIX_SCAN_RATE

#define I2C1_SCL_PIN A15
#define I2C1_SDA_PIN A14
#define I2C1_CLOCK_SPEED 400000
#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_16_9
#define OLED_BRIGHTNESS 128
#define OLED_UPDATE_INTERVAL 1000

#define ADC_RESOLUTION 12

#define CALIBRATION_RANGE 255

#define AUDIO_PIN A4
#define AUDIO_PIN_ALT_AS_NEGATIVE
#define AUDIO_PIN_ALT A5
#define AUDIO_INIT_DELAY 250
#define AUDIO_DAC_SAMPLE_MAX 4095U
#define TEMPO_DEFAULT 70
#ifdef AUDIO_ENABLE
#   define STARTUP_SONG SONG(ZELDA_PUZZLE)
#   define GOODBYE_SONG SONG()
#endif

